; IMPORTANT: DO NOT USE "BURN BOOTLOADER"
[platformio]
src_dir = firmware/src
lib_dir = firmware/lib

[env]
lib_deps =
    adafruit/Adafruit NeoPixel@=1.12.3
    chris--a/Keypad@=3.1.1

[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_speed = 115200
monitor_speed = 9600

[env:bare]
platform 			= atmelavr
board 				= ATmega328
framework 			= arduino
board_build.mcu 	= atmega328p
board_build.f_cpu 	= 8000000L
monitor_speed       = 9600
build_flags =
    -DSINGLE_BOARD="1"
    ;-DOSC_CAL=0x79    ; comment this line to disable OSCCAL override

; Settings for ICSP uploading
upload_protocol = custom
upload_flags = 
    -c 
    usbasp 
    -p 
    m328p 
    -F 
upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:a

; Recommended Fuses for bare Atmega328P (8MHz)
board_fuses.lfuse   = 0xE2
board_fuses.hfuse   = 0xDA
board_fuses.efuse   = 0xFD

[env:bare_calibration]
build_flags =
    ${env:bare.build_flags}
    -DOSC_CAL_SWEEP

extends = env:bare